INSERT INTO characters (name, ru_name, key) VALUES
  ('Barbarian', 'Варвар', 'barbarian'),
  ('Moon Elf', 'Лунная Эльфийка', 'moon-elf'),
  ('Pyromancer', 'Пиромант', 'pyromancer'),
  ('Shadow Thief', 'Теневой Вор', 'shadow-thief'),
  ('Monk', 'Монах', 'monk'),
  ('Paladin', 'Паладин', 'paladin'),
  ('Ninja', 'Ниндзя', 'ninja'),
  ('Treant', 'Энт', 'treant'),
  ('Gunslinger', 'Стрелок', 'gunslinger'),
  ('Samurai', 'Самурай', 'samurai'),
  ('Tactician', 'Тактик', 'tactician'),
  ('Huntress', 'Охотница', 'huntress'),
  ('Cursed Pirate', 'Проклятый Пират', 'cursed-pirate'),
  ('Artificier', 'Изобретатель', 'artificier'),
  ('Seraph', 'Серафим', 'seraph'),
  ('Vampire Lord', 'Королева Вампиров', 'vampire-lord');
